# Generated by Django 3.0 on 2019-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='endDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='startDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
