# Generated by Django 3.0 on 2019-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20191212_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
